//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moksh.PSAS.DataAdapter.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class people_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public people_master()
        {
            this.risk_master = new HashSet<risk_master>();
        }
    
        public int OrgID { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> LineManagerID { get; set; }
        public string LineManagerName { get; set; }
        public string LineManageremailID { get; set; }
        public string EmployeeEmailID { get; set; }
        public Nullable<long> LandlinePhone { get; set; }
        public Nullable<long> MobilePhone1 { get; set; }
        public Nullable<long> MobilePhone2 { get; set; }
        public Nullable<int> EmployeeNumber { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
        public string Updatedby { get; set; }
        public Nullable<int> Extra1 { get; set; }
        public Nullable<int> Extra2 { get; set; }
        public Nullable<int> Extra3 { get; set; }
        public Nullable<int> Extra4 { get; set; }
        public Nullable<int> Extra5 { get; set; }
        public string Extra6 { get; set; }
        public string Extra7 { get; set; }
        public string Extra8 { get; set; }
        public string Extra9 { get; set; }
        public string Extra10 { get; set; }
        public Nullable<System.DateTime> Extra11 { get; set; }
        public Nullable<System.DateTime> Extra12 { get; set; }
        public Nullable<System.DateTime> Extra13 { get; set; }
        public Nullable<System.DateTime> Extra14 { get; set; }
        public Nullable<System.DateTime> Extra15 { get; set; }
        public int peopleid { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<risk_master> risk_master { get; set; }
    }
}
