//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moksh.PSAS.DataAdapter.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class risk_master
    {
        public int RiskID { get; set; }
        public Nullable<int> OrgID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> SourceType { get; set; }
        public string SourceDetail { get; set; }
        public string Background { get; set; }
        public byte[] Attachment { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Opportunityorhreat { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> RevealIdentity { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> SubCategory { get; set; }
        public Nullable<int> InternalOrExternal { get; set; }
        public Nullable<int> ImpactedOrganisation { get; set; }
        public Nullable<int> Levell { get; set; }
        public Nullable<int> RiskOwnerID { get; set; }
        public string RiskOwnerName { get; set; }
        public string RiskOwnerEmailid { get; set; }
        public Nullable<int> SMEID { get; set; }
        public string SMEName { get; set; }
        public string SMEEmailid { get; set; }
        public Nullable<int> Probability { get; set; }
        public Nullable<int> Impact { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> InherentRiskScore { get; set; }
        public string InherentRiskgrading { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
        public string Updatedby { get; set; }
        public Nullable<int> Extra1 { get; set; }
        public Nullable<int> Extra2 { get; set; }
        public Nullable<int> Extra3 { get; set; }
        public Nullable<int> Extra4 { get; set; }
        public Nullable<int> Extra5 { get; set; }
        public string Extra6 { get; set; }
        public string Extra7 { get; set; }
        public string Extra8 { get; set; }
        public string Extra9 { get; set; }
        public string Extra10 { get; set; }
        public Nullable<System.DateTime> Extra11 { get; set; }
        public Nullable<System.DateTime> Extra12 { get; set; }
        public Nullable<System.DateTime> Extra13 { get; set; }
        public Nullable<System.DateTime> Extra14 { get; set; }
        public Nullable<System.DateTime> Extra15 { get; set; }
    
        public virtual people_master people_master { get; set; }
    }
}
